#!/bin/sh
apt_check() 
{
  if (! /usr/bin/apt-get $1)
  then
    echo $2
  exit 1
fi
}

flavor=$1
if [ "$flavor" == "stable" ]
then
  flav=""
else
  flav="-${flavor}"
fi

grep -v MDSplus /etc/apt/sources.list > /etc/apt/sources.list.save
mv -f /etc/apt/sources.list.save /etc/apt/sources.list
echo "deb http://www.mdsplus.org/dist/Ubuntu11/repo MDSplus $1" >>/etc/apt/sources.list
/usr/bin/apt-get autoremove -y "mdsplus*"
apt-check "update" "Error doing update"
apt-check "install -y mdsplus${flav}-python" "Error doing ${flavor} python install"
apt-check "autoremove -y mdsplus${flav}-python" "Error doing ${flavor} python remove"
apt-check "install -y mdsplus${flav}" "Error doing full ${flavor} install"
apt-check "autoremove -y mdsplus${flav}" "Error doing ${flavor} remove"

